## Data Visualization
- Data visualization having metplotlib, plotly, seaborn package that can be used to display the data into graphical representation
### Manupulation of data
- for data cleaning/ transformation/ analysis of data we have pandas, numpy library in python

## Numpy
- Num=number, py = python
- numpy library is very specific for working with the number
- numpy array having fast data retrival
### if we have list why we use numpy array
- list                     
1. hetroginous data                  
2. [1,2,3,'abc',]                    
3. list can store mulitple data type
4. memory allocate each one of the elements inside the list
    
- numpy
1. homogenous list
2. [1,2,3,4], [a,b,c]
3. it can store same type of dat
4. memory allocate to each element adusently

### numpy library
- it is open source library
- it can be used to perform vide variety of DS analysis
- numpy is python library working with arrays
- Numpy arrays called ndarray it means multi dimensional array
- ndarray having - 1D, 2D, 3D, 4D
    - 1D = vectors
    - 2D = Matrcis
## conda install numpy for installation of numoy


In [1]:
#importing numpy library
import numpy as np

In [2]:
#Check the version of numpy
print(np.__version__)

1.24.3


In [3]:
# create ndarray
arr = np.array([1,2,35,5,6])
arr

array([ 1,  2, 35,  5,  6])

In [4]:
arr1 = np.array(range(10))
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr2 = np.array(range(2,10))
arr2

array([2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
arr3 = np.array(range(2,10,2))

In [7]:
arr3

array([2, 4, 6, 8])

In [8]:
#How to create numpy array, 
# by using np.array function

In [12]:
#cration of 2D Array
arr2d = np.array([[1,2,3,4,5],[3,4,56,7,8]])
print(arr2d)
print(type(arr2d))

[[ 1  2  3  4  5]
 [ 3  4 56  7  8]]
<class 'numpy.ndarray'>


In [14]:
# to find the shape of Ndarray shape
# arrayname.shape is syntax
print("ndshape of arr2d",arr2d.shape)
print("ndshape of arr",arr.shape)

ndshape of arr2d (2, 5)
ndshape of arr (5,)


In [6]:
a=np.linspace(10,20,5)
print(a)

[10.  12.5 15.  17.5 20. ]


In [8]:
a1=np.linspace(0,2)
print(a1)

[0.         0.04081633 0.08163265 0.12244898 0.16326531 0.20408163
 0.24489796 0.28571429 0.32653061 0.36734694 0.40816327 0.44897959
 0.48979592 0.53061224 0.57142857 0.6122449  0.65306122 0.69387755
 0.73469388 0.7755102  0.81632653 0.85714286 0.89795918 0.93877551
 0.97959184 1.02040816 1.06122449 1.10204082 1.14285714 1.18367347
 1.2244898  1.26530612 1.30612245 1.34693878 1.3877551  1.42857143
 1.46938776 1.51020408 1.55102041 1.59183673 1.63265306 1.67346939
 1.71428571 1.75510204 1.79591837 1.83673469 1.87755102 1.91836735
 1.95918367 2.        ]


## Reshape in Array
- the reshape() methods modified existing shape but original array remain unchanged
- using arr.reshape() will give a new shape to an array without changing the data
- just reminder that when you use the reshape method, the array you want to produce needs to have the same number of elemnts as the original array

In [15]:
a3=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print("Before reshape",a3)
#a3.reshape(2,3)
print("After reshape 2 row & 3 column")
print(a3.reshape(4,3))
print("After reshape 3 row & 2 column")
print(a3.reshape(3,4))

Before reshape [ 1  2  3  4  5  6  7  8  9 10 11 12]
After reshape 2 row & 3 column
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
After reshape 3 row & 2 column
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [21]:
a4=np.array([1,2,3,4,5,6,7,8])
print("with 4D 2 row , 1 column")
print(a4.reshape(4,2,1))
print("with 4D 1 row , 2 column")
print(a4.reshape(4,1,2))

with 4D 2 row , 1 column
[[[1]
  [2]]

 [[3]
  [4]]

 [[5]
  [6]]

 [[7]
  [8]]]
with 4D 1 row , 2 column
[[[1 2]]

 [[3 4]]

 [[5 6]]

 [[7 8]]]


In [8]:
# Zero array
#- the np.zeros() ndarray can be used to initialize the zero elements array
a=np.zeros((3,2,4))
print('three group with two row and 4 column')
print(a)
print("with 3 row and 3 column")
b=np.zeros((3,3))
print(b)

three group with two row and 4 column
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
with 3 row and 3 column
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [10]:
# for ones in array:-
# np.ones((row,column)) , generates an array with the specified dimesions and data is filled with ones
aones=np.ones((3,3))
print(aones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [12]:
# for ones in array:-
# np.ones((row,column)) , generates an array with the specified dimesions and data is filled with ones
aones2=np.ones((3,3,3))
print(aones2)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [13]:
# if we want only int type data type with ones
aones3=np.ones((2,4,5),dtype=int)
print(aones3)

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


In [16]:
# if we want with initialize all values with any number
afull4 = np.full((3,3),4)
print(afull4)
print('\n')
afull5 = np.full((3,3),5)
print(afull5)
print('\n')
afull6 = np.full((3,3,3),8)
print(afull6)

[[4 4 4]
 [4 4 4]
 [4 4 4]]


[[5 5 5]
 [5 5 5]
 [5 5 5]]


[[[8 8 8]
  [8 8 8]
  [8 8 8]]

 [[8 8 8]
  [8 8 8]
  [8 8 8]]

 [[8 8 8]
  [8 8 8]
  [8 8 8]]]


In [18]:
#Eye Array:-
# the eye()function , retrun an array where all elements are equal to zero, except for the k-th diagnol , whose values are equal to 1
aeye1=np.eye(4)
print(aeye1)
print('with 4 eye')
aeye2=np.eye(5,dtype=int)
print(aeye2)
print('with 5 eye')

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
with 4 eye
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
with 5 eye


In [19]:
aeye1=np.eye(4,3,dtype=int)
print(aeye1)

[[1 0 0]
 [0 1 0]
 [0 0 1]
 [0 0 0]]


In [20]:
#identity and diagonal array:-
# the identity() function, generated square array with ones on the main diagonal whereas diag() function extract or construct diagonal array
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
np.diag(np.arange(3,7))

array([[3, 0, 0, 0],
       [0, 4, 0, 0],
       [0, 0, 5, 0],
       [0, 0, 0, 6]])

In [26]:
np.diag(np.full((4),5))

array([[5, 0, 0, 0],
       [0, 5, 0, 0],
       [0, 0, 5, 0],
       [0, 0, 0, 5]])

## Numpy Random Number
- The np.random.rand method - generate randoom no. that are uniformly distributed between 0 and 1
- The np.random.randn method - generates an array with random number that are normally distributed with mean = 0, sd = 1
- The np.random.randint method - generate randoom no. that are uniformly distributed between 0 and given number
- The np.random.uniform method - generate randoom no. that are uniformly distributed within the given range of values
- The np.random.rand method - puts the random values constant even though execute the random code for multiple files

In [27]:
#np.random.rand method
np.random.rand(3,3)

array([[0.84358588, 0.29101632, 0.96300826],
       [0.82821052, 0.29010088, 0.07250141],
       [0.26952184, 0.99740996, 0.66664821]])

In [28]:
#np.random.randn
np.random.randn(3,3)

array([[ 0.07169263,  0.36358332,  0.643952  ],
       [-1.14067047, -0.89915931,  0.40147891],
       [-1.05556544, -0.16007495,  0.3556252 ]])

In [30]:
#np.random.randn
np.random.randint(2,9)#it will provide one number

3

In [31]:
np.random.randint(0,9,6)

array([0, 0, 8, 7, 3, 6])

In [3]:
np.random.uniform(1,5,4)

array([2.49955937, 4.24543144, 1.00251818, 1.18123659])

In [5]:
np.random.uniform

<function RandomState.uniform>

## Statistical Operations

In [3]:
a=np.array(([10,20,30],[40,50,60],[70,80,90]))
b=np.array(([10,20,30],[40,50,60],[70,80,90]))
print(a)
print(b)

[[10 20 30]
 [40 50 60]
 [70 80 90]]
[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [4]:
#to access the full row
a[1:2,:]

array([[40, 50, 60]])

In [5]:
a[0:1,:]

array([[10, 20, 30]])

In [6]:
a[1:3,:]

array([[40, 50, 60],
       [70, 80, 90]])

In [8]:
#if i want all column 3
a[0:3,2:]

array([[30],
       [60],
       [90]])

In [9]:
#for reverse an array
a[::-1]

array([[70, 80, 90],
       [40, 50, 60],
       [10, 20, 30]])

In [10]:
a[::-1,::-1]

array([[90, 80, 70],
       [60, 50, 40],
       [30, 20, 10]])

In [21]:
#array flipping
#there are three types of flipping - filpr(), flip(), flipud()
arr1=np.arange(50,100).reshape(5,10)
print("original array",arr1)
print('\n can be reverse only row')
print("with flipr() function",np.fliplr(arr1))
print('\n can be reverse only column')
print("with flipud()",np.flipud(arr1))
print('\n can be reverse both row and column')
print("with flip()", np.flip(arr1))

original array [[50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]

 can be reverse only row
with flipr() function [[59 58 57 56 55 54 53 52 51 50]
 [69 68 67 66 65 64 63 62 61 60]
 [79 78 77 76 75 74 73 72 71 70]
 [89 88 87 86 85 84 83 82 81 80]
 [99 98 97 96 95 94 93 92 91 90]]

 can be reverse only column
with flipud() [[90 91 92 93 94 95 96 97 98 99]
 [80 81 82 83 84 85 86 87 88 89]
 [70 71 72 73 74 75 76 77 78 79]
 [60 61 62 63 64 65 66 67 68 69]
 [50 51 52 53 54 55 56 57 58 59]]

 can be reverse both row and column
with flip() [[99 98 97 96 95 94 93 92 91 90]
 [89 88 87 86 85 84 83 82 81 80]
 [79 78 77 76 75 74 73 72 71 70]
 [69 68 67 66 65 64 63 62 61 60]
 [59 58 57 56 55 54 53 52 51 50]]


In [24]:
#inverse data with row and column with axis, here axis = 1 means row wise & if axis = 0 means column wise
arr1=np.arange(0,50).reshape(5,10)
print("original array",arr1)
print('\n can be reverse only row')
print("with flip(), axis 1 function",np.flip(arr1, axis=1))
print('\n can be reverse only column')
print("with flip(), axis 0 function",np.flip(arr1, axis=0))

original array [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]

 can be reverse only row
with flip(), axis 1 function [[ 9  8  7  6  5  4  3  2  1  0]
 [19 18 17 16 15 14 13 12 11 10]
 [29 28 27 26 25 24 23 22 21 20]
 [39 38 37 36 35 34 33 32 31 30]
 [49 48 47 46 45 44 43 42 41 40]]

 can be reverse only column
with flip(), axis 0 function [[40 41 42 43 44 45 46 47 48 49]
 [30 31 32 33 34 35 36 37 38 39]
 [20 21 22 23 24 25 26 27 28 29]
 [10 11 12 13 14 15 16 17 18 19]
 [ 0  1  2  3  4  5  6  7  8  9]]


## transpose on array
- it means convert row into column and column into row

In [26]:
arr2=np.arange(1,10).reshape(3,3)

In [29]:
print("original array is",arr2)
print("transpose array is ",np.transpose(arr2))

original array is [[1 2 3]
 [4 5 6]
 [7 8 9]]
transpose array is  [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [30]:
arr2.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

## Rotate an array

In [32]:
np.rot90(arr2)

array([[3, 6, 9],
       [2, 5, 8],
       [1, 4, 7]])

# Stacking in array
- stackin gin array means merging one array into two horizontaly and vertically
- it can be possible when numbers of row are same in two aray

In [37]:
a=np.arange(1,10).reshape(3,3)
b=np.arange(11,20).reshape(3,3)
print("original arrays are", a , b)
print("horizontal stack",np.hstack((a,b)))
print("vertical stack",np.vstack((a,b)))

original arrays are [[1 2 3]
 [4 5 6]
 [7 8 9]] [[11 12 13]
 [14 15 16]
 [17 18 19]]
horizontal stack [[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]
vertical stack [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]


## Array Spliting

In [42]:
d=np.arange(0,24).reshape(4,6)
d

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [43]:
np.hsplit(d,3)

[array([[ 0,  1],
        [ 6,  7],
        [12, 13],
        [18, 19]]),
 array([[ 2,  3],
        [ 8,  9],
        [14, 15],
        [20, 21]]),
 array([[ 4,  5],
        [10, 11],
        [16, 17],
        [22, 23]])]

In [44]:
np.vsplit(d,2)

[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]),
 array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])]

## Filtering an array:-
- filtering an array with some condition
- for this where fucntion is used


In [48]:
arr=np.arange(0,12).reshape(3,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [49]:
np.where(arr%2==0,1,0)

array([[1, 0, 1, 0],
       [1, 0, 1, 0],
       [1, 0, 1, 0]])

In [50]:
np.where(arr>6,True,False)

array([[False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True]])

# Set operation in array


In [52]:
seta=np.arange(0,12).reshape(3,4)
setb=np.arange(6,18).reshape(3,4)

In [53]:
np.union1d(seta,setb)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [54]:
np.intersect1d(seta,setb)

array([ 6,  7,  8,  9, 10, 11])

In [55]:
np.setdiff1d(seta,setb)

array([0, 1, 2, 3, 4, 5])